# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sarbagya Kafle
tagline:          'Rhetoric, Writing, and Literature'
description:      'Rhetoric, Writing, Literature'
url:              https://sarbagyakafle.github.io
baseurl:          https://sarbagyakafle.github.io/

author:
  name:           'Sarbagya Kafle'
  url:            https://twitter.com/Sarbagya15

paginate:         5

# Custom vars
version:          2.1.0

github:          
  repo:          https://github.com/sarbagyakafle/sarbagyakafle.github.io
